// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calcKNNgraph_pearson
IntegerMatrix calcKNNgraph_pearson(NumericMatrix x, int k);
RcppExport SEXP yolo_calcKNNgraph_pearson(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(calcKNNgraph_pearson(x, k));
    return rcpp_result_gen;
END_RCPP
}
// calcKNNgraph_euclidean
IntegerMatrix calcKNNgraph_euclidean(NumericMatrix x, int k);
RcppExport SEXP yolo_calcKNNgraph_euclidean(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(calcKNNgraph_euclidean(x, k));
    return rcpp_result_gen;
END_RCPP
}
